d = int(input('Digite a quantidade de dias: '))
h = int(input('Digite a quantidade de horas: ')) 
m = int(input('Digite a quantidade de minutos: ')) 
s = int(input('Digite a quantidade de segundos: '))
total = ((d*24*60*60)+(h*60*60)+(m*60)+s)
print('O total de segundos é de', total) 
